<a href="https://colab.research.google.com/github/dataqueenpend/freecodecamp-intro-to-numpy/blob/master/NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [3]:
a

array([0, 1, 2, 3, 4])

##Array creation
 Create a numpy array of size 10, filled with zeros.

In [4]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create a numpy array with values ranging from 10 to 49

In [5]:
np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones

In [6]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])


Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [8]:
X = np.arange(4, dtype=np.int)

In [9]:
np.ones_like(X)

array([1, 1, 1, 1])


Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

In [10]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

In [11]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives.

In [12]:
np.ones([4,4], dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [13]:
X = np.array([[2,3], [6,2]], dtype=np.int)

In [14]:
np.ones_like(X, dtype=np.int)*7

array([[7, 7],
       [7, 7]])

 Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 Create a numpy array, filled with 3 random integer values between 1 and 10.

In [16]:
np.random.randint(10, size=3)

array([2, 5, 0])

Create a 3*3*3 numpy matrix, filled with random float values.

In [17]:
np.random.randn(3,3,3)

array([[[ 0.17373583,  0.1532873 ,  0.37061626],
        [-1.11025552,  3.1373675 ,  0.73653433],
        [ 0.85480429, -1.28176894,  0.69545744]],

       [[-0.97913763, -0.75826159, -0.25226564],
        [-0.26083967, -0.55540593, -0.19343238],
        [ 0.12228724, -1.43568124, -0.48264653]],

       [[ 0.59896057,  2.03071527,  1.45766346],
        [-0.37201537,  0.31471445, -0.91077508],
        [-0.22006706,  0.71755379, -1.34192348]]])

 Given the X python list convert it to an Y numpy array

In [18]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [19]:
y = np.array(X)

In [20]:
print(type(y))

<class 'numpy.ndarray'>


 Given the X numpy array, make a copy and store it on Y.

In [21]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

[5 2 3] 140066237763952


In [22]:
Y = X.copy()
print(Y, id(Y))

[5 2 3] 140066237744272


Create a numpy array with numbers from 1 to 10

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [24]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [25]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [26]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [27]:
Z = np.zeros((10,10))

In [28]:
print('%d bytes' %(Z.size * Z.itemsize))

800 bytes


In [29]:
name = 'Kikira'
print('My name is %s' %name)

My name is Kikira


In [30]:
year = 28
print('I\'m %s years old' %year)

I'm 28 years old


##Array indexation
 
 Given the X numpy array, show it's first element

In [31]:
X = np.array(['A','B','C','D','E'])

In [32]:
X[0]

'A'

Given the X numpy array, show it's last element

In [33]:
X = np.array(['A','B','C','D','E'])

In [34]:
X[-1]

'E'


 Given the X numpy array, show it's first three elements

In [35]:
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

 Given the X numpy array, show all middle elements

In [36]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

 Given the X numpy array, show the elements in reverse position


In [37]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

Given the X numpy array, show the elements in an odd position

In [38]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

Given the X numpy matrix, show the first row elements

In [39]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [40]:
X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show the last row elements

In [41]:
X[-1]

array([13, 14, 15, 16])

Given the X numpy matrix, show the first element on first row

In [42]:
X[0][0]

1

Given the X numpy matrix, show the last element on last row

In [43]:
X[-1][-1]

16

Given the X numpy matrix, show the middle row elements

In [44]:
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Given the X numpy matrix, show the first two elements on the first two rows

In [45]:
X[:2,:2]

array([[1, 2],
       [5, 6]])

Given the X numpy matrix, show the last two elements on the last two rows

In [46]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
X[2:,2:]

array([[11, 12],
       [15, 16]])

##Array manipulation
Convert the given integer numpy array to float

In [48]:
X = [-5, -3, 0, 10, 40]

In [49]:
np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

Reverse the given numpy array (first element becomes last)

In [50]:
X[::-1]

[40, 10, 0, -3, -5]

Order (sort) the given numpy array

In [51]:
X.sort()

In [52]:
X

[-5, -3, 0, 10, 40]

Given the X numpy array, set the fifth element equal to 1

In [53]:
X = np.zeros(10)

In [54]:
X[4] = 1

In [55]:
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

 Given the X numpy array, change the 50 with a 40

In [56]:
X = np.array([10, 20, 30, 50])

In [57]:
X[3] = 40
X

array([10, 20, 30, 40])


Given the X numpy matrix, change the last row with all 1

In [58]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [59]:
X[-1] = np.array([1,1,1,1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

Given the X numpy matrix, change the last item on the last row with a 0

In [60]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [61]:
X[-1, -1] = 0

In [62]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

Given the X numpy matrix, add 5 to every element

In [63]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [64]:
X + 5


array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

###Boolean arrays (also called masks)
Given the X numpy array, make a mask showing negative elements

In [65]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [66]:
mask = X < 0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

Given the X numpy array, get the negative elements

In [67]:
X[mask]

array([-1, -4, -9])

Given the X numpy array, get numbers higher than 5

In [70]:
mask = X>5

In [71]:
X[mask]

array([ 6, 10])

Given the X numpy array, get numbers higher than the elements mean

In [74]:
mask = X > np.mean(X)

In [75]:
X[mask]

array([ 2,  5,  6, 10])

Given the X numpy array, get numbers equal to 2 or 10

In [78]:
mask =(X == 2) | (X == 10)

In [79]:
X[mask]

array([ 2, 10])

###Logic functions
Given the X numpy array, return True if none of its elements is zero

In [80]:
X.all()

False

Given the X numpy array, return True if any of its elements is zero

In [81]:
X.any()

True