<a href="https://colab.research.google.com/github/dataqueenpend/freecodecamp-intro-to-numpy/blob/master/NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [2]:
a

array([0, 1, 2, 3, 4])

##Array creation
 Create a numpy array of size 10, filled with zeros.

In [3]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create a numpy array with values ranging from 10 to 49

In [4]:
np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones

In [5]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])


Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
X = np.arange(4, dtype=np.int)

In [8]:
np.ones_like(X)

array([1, 1, 1, 1])


Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

In [9]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

In [10]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
np.ones([4,4], dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [12]:
X = np.array([[2,3], [6,2]], dtype=np.int)

In [13]:
np.ones_like(X, dtype=np.int)*7

array([[7, 7],
       [7, 7]])

 Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 Create a numpy array, filled with 3 random integer values between 1 and 10.

In [15]:
np.random.randint(10, size=3)

array([8, 0, 3])

Create a 3*3*3 numpy matrix, filled with random float values.

In [16]:
np.random.randn(3,3,3)

array([[[-0.34211442,  0.39035958, -0.29394454],
        [ 0.82071278,  0.90272783,  1.15490796],
        [-1.3932357 ,  1.22828124,  0.67722169]],

       [[ 0.35090788,  0.72745177,  0.56468997],
        [-0.26908664,  1.32796587, -0.12740436],
        [-0.55955241, -1.24265202, -2.20771857]],

       [[ 0.42314539, -0.4743506 , -0.30723745],
        [-0.10245865,  0.46046336,  0.52554284],
        [ 0.18717307,  0.33721198,  0.21613777]]])

 Given the X python list convert it to an Y numpy array

In [17]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [18]:
y = np.array(X)

In [19]:
print(type(y))

<class 'numpy.ndarray'>


 Given the X numpy array, make a copy and store it on Y.

In [20]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

[5 2 3] 139630461962480


In [21]:
Y = X.copy()
print(Y, id(Y))

[5 2 3] 139630498035312


Create a numpy array with numbers from 1 to 10

In [22]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [23]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [24]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [25]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [26]:
Z = np.zeros((10,10))

In [27]:
print('%d bytes' %(Z.size * Z.itemsize))

800 bytes


In [28]:
name = 'Kikira'
print('My name is %s' %name)

My name is Kikira


In [29]:
year = 28
print('I\'m %s years old' %year)

I'm 28 years old


##Array indexation
 
 Given the X numpy array, show it's first element

In [30]:
X = np.array(['A','B','C','D','E'])

In [32]:
X[0]

'A'

Given the X numpy array, show it's last element

In [33]:
X = np.array(['A','B','C','D','E'])

In [34]:
X[-1]

'E'


 Given the X numpy array, show it's first three elements

In [37]:
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

 Given the X numpy array, show all middle elements

In [38]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

 Given the X numpy array, show the elements in reverse position


In [39]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

Given the X numpy array, show the elements in an odd position

In [40]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

Given the X numpy matrix, show the first row elements

In [41]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [42]:
X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show the last row elements

In [43]:
X[-1]

array([13, 14, 15, 16])

Given the X numpy matrix, show the first element on first row

In [44]:
X[0][0]

1

Given the X numpy matrix, show the last element on last row

In [45]:
X[-1][-1]

16

Given the X numpy matrix, show the middle row elements

In [46]:
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Given the X numpy matrix, show the first two elements on the first two rows

In [48]:
X[:2,:2]

array([[1, 2],
       [5, 6]])

Given the X numpy matrix, show the last two elements on the last two rows

In [51]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
X[2:,2:]

array([[11, 12],
       [15, 16]])

##Array manipulation
Convert the given integer numpy array to float