<a href="https://colab.research.google.com/github/dataqueenpend/freecodecamp-intro-to-numpy/blob/master/NumPy_exercises-practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [2]:
a

array([0, 1, 2, 3, 4])

##Array creation
 Create a numpy array of size 10, filled with zeros.

In [3]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create a numpy array with values ranging from 10 to 49

In [4]:
np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones

In [5]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])


Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
X = np.arange(4, dtype=np.int)

In [8]:
np.ones_like(X)

array([1, 1, 1, 1])


Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

In [9]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

In [10]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
np.ones([4,4], dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [12]:
X = np.array([[2,3], [6,2]], dtype=np.int)

In [13]:
np.ones_like(X, dtype=np.int)*7

array([[7, 7],
       [7, 7]])

 Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 Create a numpy array, filled with 3 random integer values between 1 and 10.

In [15]:
np.random.randint(10, size=3)

array([6, 5, 4])

Create a 3*3*3 numpy matrix, filled with random float values.

In [16]:
np.random.randn(3,3,3)

array([[[ 2.49795809,  1.82208975, -1.49857506],
        [-0.54127247,  0.99907662, -0.415504  ],
        [ 0.39621229, -0.65683187, -0.29013456]],

       [[-2.36367363,  1.0698202 ,  2.73597208],
        [ 0.45621833,  0.12630892,  0.36047773],
        [ 0.04184961, -0.70956094,  1.34335757]],

       [[-1.21531676,  0.01793596, -1.97802865],
        [ 0.40099273,  0.30849971,  1.72699127],
        [-0.5702427 , -0.56404251,  0.4879614 ]]])

 Given the X python list convert it to an Y numpy array

In [17]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [18]:
y = np.array(X)

In [19]:
print(type(y))

<class 'numpy.ndarray'>


 Given the X numpy array, make a copy and store it on Y.

In [20]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

[5 2 3] 140277608554288


In [21]:
Y = X.copy()
print(Y, id(Y))

[5 2 3] 140277608524496


Create a numpy array with numbers from 1 to 10

In [26]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [28]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [32]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [35]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [36]:
Z = np.zeros((10,10))

In [37]:
print('%d bytes' %(Z.size * Z.itemsize))

800 bytes


In [40]:
name = 'Kikira'
print('My name is %s' %name)

My name is Kikira


In [42]:
year = 28
print('I\'m %s years old' %year)

I'm 28 year old


##Array indexation
 
 Given the X numpy array, show it's first element