<a href="https://colab.research.google.com/github/dataqueenpend/freecodecamp-intro-to-numpy/blob/master/NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [2]:
a

array([0, 1, 2, 3, 4])

##Array creation
 Create a numpy array of size 10, filled with zeros.

In [3]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create a numpy array with values ranging from 10 to 49

In [4]:
np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones

In [5]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])


Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
X = np.arange(4, dtype=np.int)

In [8]:
np.ones_like(X)

array([1, 1, 1, 1])


Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

In [9]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

In [10]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
np.ones([4,4], dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [12]:
X = np.array([[2,3], [6,2]], dtype=np.int)

In [13]:
np.ones_like(X, dtype=np.int)*7

array([[7, 7],
       [7, 7]])

 Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 Create a numpy array, filled with 3 random integer values between 1 and 10.

In [15]:
np.random.randint(10, size=3)

array([7, 0, 2])

Create a 3*3*3 numpy matrix, filled with random float values.

In [16]:
np.random.randn(3,3,3)

array([[[-0.90215844,  0.25575084,  0.05051102],
        [ 1.50599284,  0.73291407,  0.76249139],
        [-0.11811468, -0.90243326, -0.49582339]],

       [[-0.31841575,  0.12790312,  2.44502776],
        [-1.86829695,  0.54172786, -0.30905054],
        [-0.77896687,  0.88606855, -0.18087959]],

       [[-0.21585398, -1.62043054, -1.44371334],
        [-1.63064642,  2.73701777, -0.35334232],
        [ 0.24899283,  0.58080839, -0.85631234]]])

 Given the X python list convert it to an Y numpy array

In [17]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [18]:
y = np.array(X)

In [19]:
print(type(y))

<class 'numpy.ndarray'>


 Given the X numpy array, make a copy and store it on Y.

In [20]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

[5 2 3] 140008871676944


In [21]:
Y = X.copy()
print(Y, id(Y))

[5 2 3] 140008871695584


Create a numpy array with numbers from 1 to 10

In [22]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [23]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [24]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [25]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [26]:
Z = np.zeros((10,10))

In [27]:
print('%d bytes' %(Z.size * Z.itemsize))

800 bytes


In [28]:
name = 'Kikira'
print('My name is %s' %name)

My name is Kikira


In [29]:
year = 28
print('I\'m %s years old' %year)

I'm 28 years old


##Array indexation
 
 Given the X numpy array, show it's first element

In [30]:
X = np.array(['A','B','C','D','E'])

In [31]:
X[0]

'A'

Given the X numpy array, show it's last element

In [32]:
X = np.array(['A','B','C','D','E'])

In [33]:
X[-1]

'E'


 Given the X numpy array, show it's first three elements

In [34]:
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

 Given the X numpy array, show all middle elements

In [35]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

 Given the X numpy array, show the elements in reverse position


In [36]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

Given the X numpy array, show the elements in an odd position

In [37]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

Given the X numpy matrix, show the first row elements

In [38]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [39]:
X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show the last row elements

In [40]:
X[-1]

array([13, 14, 15, 16])

Given the X numpy matrix, show the first element on first row

In [41]:
X[0][0]

1

Given the X numpy matrix, show the last element on last row

In [42]:
X[-1][-1]

16

Given the X numpy matrix, show the middle row elements

In [43]:
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Given the X numpy matrix, show the first two elements on the first two rows

In [44]:
X[:2,:2]

array([[1, 2],
       [5, 6]])

Given the X numpy matrix, show the last two elements on the last two rows

In [45]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
X[2:,2:]

array([[11, 12],
       [15, 16]])

##Array manipulation
Convert the given integer numpy array to float

In [47]:
X = [-5, -3, 0, 10, 40]

In [49]:
np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

Reverse the given numpy array (first element becomes last)

In [50]:
X[::-1]

[40, 10, 0, -3, -5]

Order (sort) the given numpy array

In [52]:
X.sort()

In [53]:
X

[-5, -3, 0, 10, 40]

Given the X numpy array, set the fifth element equal to 1

In [54]:
X = np.zeros(10)

In [55]:
X[4] = 1

In [57]:
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

 Given the X numpy array, change the 50 with a 40

In [59]:
X = np.array([10, 20, 30, 50])

In [60]:
X[3] = 40
X

array([10, 20, 30, 40])


Given the X numpy matrix, change the last row with all 1

In [61]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [63]:
X[-1] = np.array([1,1,1,1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

Given the X numpy matrix, change the last item on the last row with a 0

In [64]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [66]:
X[-1, -1] = 0

In [67]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

Given the X numpy matrix, add 5 to every element

In [68]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [70]:
X + 5


array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])